server:
  port: 9999
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    url: jdbc:mysql://120.26.138.131:3326/test_db?useUnicode=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: rootmima
    driver-class-name: com.mysql.cj.jdbc.Driver
